spring.application.name=SB19-Hotel-Management-System
server.port = 9090
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/capgdb
spring.datasource.username=root
spring.datasource.password=0703